experiment_folder:
  "/g/boulard/Projects/BS_EMSeq/"
input_samples_table:
  "data/sequencing/samples_table.csv"
fastq_input_dir:
  "data/sequencing/fastq/"
seq_output_dir:
  "data/sequencing/"
genome_dir:
  "data/genome/Mus_musculus/" #primary assembly fasta of GRCm38_v100 from ensemble
genome_fa:
  "data/genome/GRCm38.p6.genome.fa"
chr_sizes:
  "data/genome/mm10.chrom.sizes.txt"
maj_chr_bed:
  "data/genome/mm10_maj_chr.bed"
gene_annotation_bed:
  "data/annotations/gencode.vM25.annotation.bed"
CGI_annotation_bed:
  "data/annotations/UCSC_CGI_mm10.bed"
TE_annotation_bed:
  "data/annotations/RepeatMasker_RepeatLibrary20140131_mm10.bed"
analysis_output_dir:
  "analysis/"
tmp_dir:
  "tmp/"
envs_folder:
  "/g/boulard/Projects/BS_EMSeq/env/conda/"
script_dir:
  "src/"
containers_folder:
  "/g/boulard/Projects/BS_EMSeq/singularity/containers/"
